services:
  ratings:
    build: .
    image: ghcr.io/gun082544/bookinfo-ratings:prd
    ports:
      - "8081:8081"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/?authSource=ratings
      MONGO_DB_NAME: ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:4.4.4-debian-10-r5
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
