ratings:
  namespace: gun-bookinfo-uat
  image: ghcr.io/gun082544/bookinfo-ratings
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-uat-ratings-mongodb-secret
ingress:
  host: bookinfo.uat.hellodolphin.in.th
  path: "/gun/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017/ratings
