ratings:
  namespace: gun-bookinfo-prd
  image: ghcr.io/gun082544/bookinfo-ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-prd-ratings-mongodb-secret
ingress:
  host: bookinfo.hellodolphin.in.th
  path: "/gun/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/?authSource=ratings
  MONGO_DB_NAME: ratings