apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ratings-gun
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
       paths:
       - path: /gun/ratings(/|$)(.*)
         pathType: Prefix
         backend:
          service:
             name: gun-ratings-uat
             port:
              number: 8081