apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: book
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: gun-ratings-uat
          servicePort: 8081