apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service1
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /service2
        backend:
          serviceName: gun-ratings-uat
          servicePort: 8080
