apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bookinfo-ratings-gun
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
    - http:
       paths:
       - path: /gun/ratings
         backend:
             serviceName: gun-ratings-uat
             servicePort: 8081