apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bookinfo-ratings-gun
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
       paths:
       - path: 
         backend:
             ServiceName: gun-ratings-uat
             ServicePort: 8081