apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gun-ratings-uat
  namespace: gun-bookinfo-uat
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /gun/ratings(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: gun-ratings-uat
          servicePort: 8081
